/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_lpv_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

static const casadi_real casadi_c0[6] = {-8.3333333333333339e-04, 0., 2.2222222222222222e-03, 8.3333333333333339e-04, 0., 2.2222222222222222e-03};

/* f_lpv:(x[3],u[2],delta,vx0)->(xdot[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+3, w01, w02, w03, w04, *w05=w+10, *w06=w+13, w07, *w08=w+17, *w09=w+20, *w10=w+29;
  casadi_real *w11=w+38, *w12=w+44;
  const casadi_real *cs, *ct;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w00, 3);
  /* #1: @1 = -320000 */
  w01 = -320000.;
  /* #2: @2 = 3000 */
  w02 = 3000.;
  /* #3: @3 = input[3][0] */
  w03 = arg[3] ? arg[3][0] : 0;
  /* #4: @2 = (@2*@3) */
  w02 *= w03;
  /* #5: @1 = (@1/@2) */
  w01 /= w02;
  /* #6: @2 = 10.6667 */
  w02 = 1.0666666666666666e+01;
  /* #7: @4 = 0 */
  w04 = 0.;
  /* #8: @5 = horzcat(@1, @2, @4) */
  rr=w05;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  /* #9: @5 = @5' */
  /* #10: @1 = -224000 */
  w01 = -224000.;
  /* #11: @2 = 1500 */
  w02 = 1500.;
  /* #12: @4 = sq(@3) */
  w04 = casadi_sq( w03 );
  /* #13: @2 = (@2*@4) */
  w02 *= w04;
  /* #14: @1 = (@1/@2) */
  w01 /= w02;
  /* #15: @2 = 1 */
  w02 = 1.;
  /* #16: @1 = (@1-@2) */
  w01 -= w02;
  /* #17: @2 = -160000 */
  w02 = -160000.;
  /* #18: @4 = 1500 */
  w04 = 1500.;
  /* #19: @4 = (@4*@3) */
  w04 *= w03;
  /* #20: @2 = (@2/@4) */
  w02 /= w04;
  /* #21: @4 = 0 */
  w04 = 0.;
  /* #22: @6 = horzcat(@1, @2, @4) */
  rr=w06;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  /* #23: @6 = @6' */
  /* #24: @1 = 0 */
  w01 = 0.;
  /* #25: @2 = 0 */
  w02 = 0.;
  /* #26: @4 = -0.8085 */
  w04 = -8.0850000000000011e-01;
  /* #27: @4 = (@4*@3) */
  w04 *= w03;
  /* #28: @7 = 1500 */
  w07 = 1500.;
  /* #29: @4 = (@4/@7) */
  w04 /= w07;
  /* #30: @8 = horzcat(@1, @2, @4) */
  rr=w08;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  /* #31: @8 = @8' */
  /* #32: @9 = horzcat(@5, @6, @8) */
  rr=w09;
  for (i=0, cs=w05; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w06; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w08; i<3; ++i) *rr++ = *cs++;
  /* #33: @10 = @9' */
  for (i=0, rr=w10, cs=w09; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #34: @1 = input[0][0] */
  w01 = arg[0] ? arg[0][0] : 0;
  /* #35: @2 = input[0][1] */
  w02 = arg[0] ? arg[0][1] : 0;
  /* #36: @4 = input[0][2] */
  w04 = arg[0] ? arg[0][2] : 0;
  /* #37: @5 = vertcat(@1, @2, @4) */
  rr=w05;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  /* #38: @0 = mac(@10,@5,@0) */
  for (i=0, rr=w00; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w10+j, ct=w05+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #39: @5 = zeros(3x1) */
  casadi_clear(w05, 3);
  /* #40: @11 = 
  [[-0.000833333, 0.000833333], 
   [0, 0], 
   [0.00222222, 0.00222222]] */
  casadi_copy(casadi_c0, 6, w11);
  /* #41: @1 = input[1][0] */
  w01 = arg[1] ? arg[1][0] : 0;
  /* #42: @2 = input[1][1] */
  w02 = arg[1] ? arg[1][1] : 0;
  /* #43: @12 = vertcat(@1, @2) */
  rr=w12;
  *rr++ = w01;
  *rr++ = w02;
  /* #44: @5 = mac(@11,@12,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=w12+i*2; k<2; ++k) *rr += cs[k*3]**ct++;
  /* #45: @0 = (@0+@5) */
  for (i=0, rr=w00, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #46: @1 = 32 */
  w01 = 32.;
  /* #47: @2 = 80000 */
  w02 = 80000.;
  /* #48: @4 = 1500 */
  w04 = 1500.;
  /* #49: @4 = (@4*@3) */
  w04 *= w03;
  /* #50: @2 = (@2/@4) */
  w02 /= w04;
  /* #51: @4 = 0 */
  w04 = 0.;
  /* #52: @5 = vertcat(@1, @2, @4) */
  rr=w05;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  /* #53: @1 = input[2][0] */
  w01 = arg[2] ? arg[2][0] : 0;
  /* #54: @5 = (@5*@1) */
  for (i=0, rr=w05; i<3; ++i) (*rr++) *= w01;
  /* #55: @0 = (@0+@5) */
  for (i=0, rr=w00, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #56: @1 = 0 */
  w01 = 0.;
  /* #57: @2 = 0 */
  w02 = 0.;
  /* #58: @4 = 0.8085 */
  w04 = 8.0850000000000011e-01;
  /* #59: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #60: @4 = (@4*@3) */
  w04 *= w03;
  /* #61: @3 = 3000 */
  w03 = 3000.;
  /* #62: @4 = (@4/@3) */
  w04 /= w03;
  /* #63: @3 = 0.14715 */
  w03 = 1.4715000000000000e-01;
  /* #64: @4 = (@4-@3) */
  w04 -= w03;
  /* #65: @5 = vertcat(@1, @2, @4) */
  rr=w05;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w04;
  /* #66: @0 = (@0+@5) */
  for (i=0, rr=w00, cs=w05; i<3; ++i) (*rr++) += (*cs++);
  /* #67: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f_lpv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_lpv_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_lpv_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_lpv_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_lpv_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_lpv_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_lpv_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_lpv_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_lpv_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_lpv_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_lpv_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_lpv_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    case 2: return "delta";
    case 3: return "vx0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_lpv_name_out(casadi_int i) {
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_lpv_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_lpv_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_lpv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 46;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_lpv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 46*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
