/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int nlplant_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int nlplant_f_alloc_mem(void);
int nlplant_f_init_mem(int mem);
void nlplant_f_free_mem(int mem);
int nlplant_f_checkout(void);
void nlplant_f_release(int mem);
void nlplant_f_incref(void);
void nlplant_f_decref(void);
casadi_int nlplant_f_n_in(void);
casadi_int nlplant_f_n_out(void);
casadi_real nlplant_f_default_in(casadi_int i);
const char* nlplant_f_name_in(casadi_int i);
const char* nlplant_f_name_out(casadi_int i);
const casadi_int* nlplant_f_sparsity_in(casadi_int i);
const casadi_int* nlplant_f_sparsity_out(casadi_int i);
int nlplant_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int nlplant_f_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define nlplant_f_SZ_ARG 4
#define nlplant_f_SZ_RES 2
#define nlplant_f_SZ_IW 0
#define nlplant_f_SZ_W 20
#ifdef __cplusplus
} /* extern "C" */
#endif
