/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nlplant_f_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};

/* nlplant_f:(i0[6],i1[5])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w03, w04, *w05=w+10, w06, w07, w08, w09, w10;
  const casadi_real *cs;
  /* #0: @0 = -80000 */
  w00 = -80000.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 6, w01);
  /* #2: @2 = @1[0] */
  for (rr=(&w02), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #3: @3 = 1.2 */
  w03 = 1.2000000000000000e+00;
  /* #4: @4 = @1[1] */
  for (rr=(&w04), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #5: @3 = (@3*@4) */
  w03 *= w04;
  /* #6: @3 = (@2+@3) */
  w03  = (w02+w03);
  /* #7: @5 = input[1][0] */
  casadi_copy(arg[1], 5, w05);
  /* #8: @6 = @5[0] */
  for (rr=(&w06), cs=w05+0; cs!=w05+1; cs+=1) *rr++ = *cs;
  /* #9: @7 = cos(@6) */
  w07 = cos( w06 );
  /* #10: @7 = (@3*@7) */
  w07  = (w03*w07);
  /* #11: @8 = 20 */
  w08 = 20.;
  /* #12: @9 = 0.75 */
  w09 = 7.5000000000000000e-01;
  /* #13: @9 = (@9*@4) */
  w09 *= w04;
  /* #14: @8 = (@8-@9) */
  w08 -= w09;
  /* #15: @9 = sin(@6) */
  w09 = sin( w06 );
  /* #16: @9 = (@8*@9) */
  w09  = (w08*w09);
  /* #17: @7 = (@7-@9) */
  w07 -= w09;
  /* #18: @9 = cos(@6) */
  w09 = cos( w06 );
  /* #19: @8 = (@8*@9) */
  w08 *= w09;
  /* #20: @9 = sin(@6) */
  w09 = sin( w06 );
  /* #21: @3 = (@3*@9) */
  w03 *= w09;
  /* #22: @8 = (@8+@3) */
  w08 += w03;
  /* #23: @7 = (@7/@8) */
  w07 /= w08;
  /* #24: @0 = (@0*@7) */
  w00 *= w07;
  /* #25: @7 = -80000 */
  w07 = -80000.;
  /* #26: @8 = 1.2 */
  w08 = 1.2000000000000000e+00;
  /* #27: @8 = (@8*@4) */
  w08 *= w04;
  /* #28: @8 = (@2+@8) */
  w08  = (w02+w08);
  /* #29: @3 = cos(@6) */
  w03 = cos( w06 );
  /* #30: @3 = (@8*@3) */
  w03  = (w08*w03);
  /* #31: @9 = 20 */
  w09 = 20.;
  /* #32: @10 = -0.75 */
  w10 = -7.5000000000000000e-01;
  /* #33: @10 = (@10*@4) */
  w10 *= w04;
  /* #34: @9 = (@9-@10) */
  w09 -= w10;
  /* #35: @10 = sin(@6) */
  w10 = sin( w06 );
  /* #36: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #37: @3 = (@3-@10) */
  w03 -= w10;
  /* #38: @10 = cos(@6) */
  w10 = cos( w06 );
  /* #39: @9 = (@9*@10) */
  w09 *= w10;
  /* #40: @10 = sin(@6) */
  w10 = sin( w06 );
  /* #41: @8 = (@8*@10) */
  w08 *= w10;
  /* #42: @9 = (@9+@8) */
  w09 += w08;
  /* #43: @3 = (@3/@9) */
  w03 /= w09;
  /* #44: @7 = (@7*@3) */
  w07 *= w03;
  /* #45: @3 = (@0+@7) */
  w03  = (w00+w07);
  /* #46: @6 = cos(@6) */
  w06 = cos( w06 );
  /* #47: @3 = (@3*@6) */
  w03 *= w06;
  /* #48: @6 = -80000 */
  w06 = -80000.;
  /* #49: @9 = -1.6 */
  w09 = -1.6000000000000001e+00;
  /* #50: @9 = (@9*@4) */
  w09 *= w04;
  /* #51: @9 = (@2+@9) */
  w09  = (w02+w09);
  /* #52: @8 = 20 */
  w08 = 20.;
  /* #53: @10 = 0.75 */
  w10 = 7.5000000000000000e-01;
  /* #54: @10 = (@10*@4) */
  w10 *= w04;
  /* #55: @8 = (@8-@10) */
  w08 -= w10;
  /* #56: @9 = (@9/@8) */
  w09 /= w08;
  /* #57: @6 = (@6*@9) */
  w06 *= w09;
  /* #58: @3 = (@3+@6) */
  w03 += w06;
  /* #59: @9 = -80000 */
  w09 = -80000.;
  /* #60: @8 = -1.6 */
  w08 = -1.6000000000000001e+00;
  /* #61: @8 = (@8*@4) */
  w08 *= w04;
  /* #62: @2 = (@2+@8) */
  w02 += w08;
  /* #63: @8 = 20 */
  w08 = 20.;
  /* #64: @10 = -0.75 */
  w10 = -7.5000000000000000e-01;
  /* #65: @10 = (@10*@4) */
  w10 *= w04;
  /* #66: @8 = (@8-@10) */
  w08 -= w10;
  /* #67: @2 = (@2/@8) */
  w02 /= w08;
  /* #68: @9 = (@9*@2) */
  w09 *= w02;
  /* #69: @3 = (@3+@9) */
  w03 += w09;
  /* #70: @2 = 1500 */
  w02 = 1500.;
  /* #71: @3 = (@3/@2) */
  w03 /= w02;
  /* #72: @2 = 20 */
  w02 = 20.;
  /* #73: @2 = (@2*@4) */
  w02 *= w04;
  /* #74: @3 = (@3-@2) */
  w03 -= w02;
  /* #75: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #76: @3 = 1.2 */
  w03 = 1.2000000000000000e+00;
  /* #77: @0 = (@0+@7) */
  w00 += w07;
  /* #78: @3 = (@3*@0) */
  w03 *= w00;
  /* #79: @0 = 1.6 */
  w00 = 1.6000000000000001e+00;
  /* #80: @6 = (@6+@9) */
  w06 += w09;
  /* #81: @0 = (@0*@6) */
  w00 *= w06;
  /* #82: @3 = (@3-@0) */
  w03 -= w00;
  /* #83: @0 = 0.75 */
  w00 = 7.5000000000000000e-01;
  /* #84: @6 = @5[4] */
  for (rr=(&w06), cs=w05+4; cs!=w05+5; cs+=1) *rr++ = *cs;
  /* #85: @9 = 0.3 */
  w09 = 2.9999999999999999e-01;
  /* #86: @9 = (@6/@9) */
  w09  = (w06/w09);
  /* #87: @7 = @5[3] */
  for (rr=(&w07), cs=w05+3; cs!=w05+4; cs+=1) *rr++ = *cs;
  /* #88: @2 = 0.3 */
  w02 = 2.9999999999999999e-01;
  /* #89: @2 = (@7/@2) */
  w02  = (w07/w02);
  /* #90: @4 = (@9-@2) */
  w04  = (w09-w02);
  /* #91: @0 = (@0*@4) */
  w00 *= w04;
  /* #92: @3 = (@3+@0) */
  w03 += w00;
  /* #93: @0 = 2500 */
  w00 = 2500.;
  /* #94: @3 = (@3/@0) */
  w03 /= w00;
  /* #95: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #96: @3 = @5[1] */
  for (rr=(&w03), cs=w05+1; cs!=w05+2; cs+=1) *rr++ = *cs;
  /* #97: @0 = 1.2 */
  w00 = 1.2000000000000000e+00;
  /* #98: @3 = (@3/@0) */
  w03 /= w00;
  /* #99: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #100: @3 = @5[2] */
  for (rr=(&w03), cs=w05+2; cs!=w05+3; cs+=1) *rr++ = *cs;
  /* #101: @0 = 1.2 */
  w00 = 1.2000000000000000e+00;
  /* #102: @3 = (@3/@0) */
  w03 /= w00;
  /* #103: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #104: @3 = 0.3 */
  w03 = 2.9999999999999999e-01;
  /* #105: @3 = (@3*@2) */
  w03 *= w02;
  /* #106: @7 = (@7-@3) */
  w07 -= w03;
  /* #107: @3 = 1.2 */
  w03 = 1.2000000000000000e+00;
  /* #108: @7 = (@7/@3) */
  w07 /= w03;
  /* #109: output[0][4] = @7 */
  if (res[0]) res[0][4] = w07;
  /* #110: @7 = 0.3 */
  w07 = 2.9999999999999999e-01;
  /* #111: @7 = (@7*@9) */
  w07 *= w09;
  /* #112: @6 = (@6-@7) */
  w06 -= w07;
  /* #113: @7 = 1.2 */
  w07 = 1.2000000000000000e+00;
  /* #114: @6 = (@6/@7) */
  w06 /= w07;
  /* #115: output[0][5] = @6 */
  if (res[0]) res[0][5] = w06;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlplant_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlplant_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlplant_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlplant_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlplant_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlplant_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlplant_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlplant_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlplant_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlplant_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlplant_f_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlplant_f_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlplant_f_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlplant_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlplant_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlplant_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 20;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlplant_f_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 20*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
