/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int f_lpv_discrete(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int f_lpv_discrete_alloc_mem(void);
int f_lpv_discrete_init_mem(int mem);
void f_lpv_discrete_free_mem(int mem);
int f_lpv_discrete_checkout(void);
void f_lpv_discrete_release(int mem);
void f_lpv_discrete_incref(void);
void f_lpv_discrete_decref(void);
casadi_int f_lpv_discrete_n_in(void);
casadi_int f_lpv_discrete_n_out(void);
casadi_real f_lpv_discrete_default_in(casadi_int i);
const char* f_lpv_discrete_name_in(casadi_int i);
const char* f_lpv_discrete_name_out(casadi_int i);
const casadi_int* f_lpv_discrete_sparsity_in(casadi_int i);
const casadi_int* f_lpv_discrete_sparsity_out(casadi_int i);
int f_lpv_discrete_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int f_lpv_discrete_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define f_lpv_discrete_SZ_ARG 6
#define f_lpv_discrete_SZ_RES 2
#define f_lpv_discrete_SZ_IW 0
#define f_lpv_discrete_SZ_W 32
#ifdef __cplusplus
} /* extern "C" */
#endif
